# Build

name: Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: R ${{ matrix.config.r }} | ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-20.04,  r: 'release'}
    
    steps:
      - uses: actions/checkout@v2
      #R Set-up
      - name: Set up R ${{ matrix.config.r }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
      #Install dependencies
      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
      #Check R Package
      - name: Check R package
        uses: r-lib/actions/check-r-package@v2
        with:
          artifact-name: thredds_r-${{ matrix.config.r }}_${{ matrix.config.os }}-results
